### ISSUE TITLE
Page shaking when opening a modal or dialog

### ISSUE THREAD

**Issue by yzhang-eightfold** [EightfoldAI/octuple#480] opened 2022-12-28 02:23 UTC
Caused by the disappearing of the page scrollbar

TM:
https://user-images.githubusercontent.com/60897218/209746456-baf88d28-9814-4c29-a8f9-7d84fa477592.mov

TA:
https://user-images.githubusercontent.com/60897218/209747265-4b8b73c3-85dc-4950-8fff-329442576225.mov

reproducible in sandbox too
https://codesandbox.io/s/dialog-forked-vbqspb?file=/demo.js

**Comment by dkilgore-eightfold** [comment] 2023-01-03 18:54
This is caused by the width of the scrollbar not being present as modals should never allow page scroll below the overlay. Minor issue as the horizontal pixel shift is expected. However, there may be some way to mitigate the ~18 pixel shift.

**Comment by dkilgore-eightfold** [comment] 2023-03-30 22:55
Closing as @yzhang-eightfold observed issue no longer repros in vscode apps.

**Closed by dkilgore-eightfold** 2023-03-30 22:55 UTC
Labels: bug
