### ISSUE TITLE
Table shows two scroll bars

### ISSUE THREAD

**Issue by areddy-eightfold** [EightfoldAI/octuple#352] opened 2022-09-08 14:40 UTC
![image](https://user-images.githubusercontent.com/84381377/189151638-25879fa8-6e5d-425e-a219-935632aaddb8.png)

**Comment by dkilgore-eightfold** [comment] 2022-09-08 19:16
@areddy-eightfold Please provide a [codesandbox](https://codesandbox.io/) repro.

**Comment by dkilgore-eightfold** [comment] 2022-09-13 00:06
@areddy-eightfold Will repro and debug.

**Comment by dkilgore-eightfold** [comment] 2022-09-23 23:28
Found the root cause. Fix is out for review as part of https://github.com/EightfoldAI/octuple/pull/389

**Comment by dkilgore-eightfold** [comment] 2022-09-26 17:09
Fix merged as part of https://github.com/EightfoldAI/octuple/pull/389

**Closed by dkilgore-eightfold** 2022-09-26 17:09 UTC
Labels: bug, ticketed-internal
